@echo off
setlocal enabledelayedexpansion
rem call lib\tbp-core\load-libs.bat
REM tbp-uncd.bat generated by TBP Core

set exit-string=%~1
set exit-string=%exit-string:/=\%
set exit-dir=
for %%F in ("%exit-string:\=" "%") do (
  set folder=%%F
  if defined exit-dir (
    set exit-dir=!folder:"=!\!exit-dir!
  ) else (
    set exit-dir=!folder:"=!
  )
)

for %%F in ("%exit-dir:\=" "%") do (
  call :uncd !cd! %%F
  if !error!==1 (
    goto cleanup
  )
)
goto cleanup

:uncd
  rem %1:cd %2:dir-to-exit
  if "%~n1"=="%~2" (
    cd ..
  ) else (
    echo You are not in a folder called "%~2".
    set error=1
    goto :eof
  )
goto :eof

:cleanup
set error=
set exit-dir=
goto :eof
