rem @echo off
setlocal enabledelayedexpansion
call lib\tbp-core\load-libs.bat
REM tbp-uncd.bat generated by TBP Core

set exit-string=%~1
for %%G in ("%exit-string:\=" "%") do (
set exit-dir=%%G\!exit-dir!
)
echo %exit-dir%
goto :eof
